/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.treasury.report.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author wflores
 */
@StyleSheet
@Template(FormPage.class)
public class ItemAccountReportInitPage extends javax.swing.JPanel {

    /**
     * Creates new form ItemAccountReportInitPage
     */
    public ItemAccountReportInitPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        xPanel2 = new com.rameses.rcp.control.XPanel();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        jPanel1 = new javax.swing.JPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xComboBox8 = new com.rameses.rcp.control.XComboBox();
        xComboBox7 = new com.rameses.rcp.control.XComboBox();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        xDateField3 = new com.rameses.rcp.control.XDateField();
        jPanel3 = new javax.swing.JPanel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        jPanel4 = new javax.swing.JPanel();
        xButton1 = new com.rameses.rcp.control.XButton();
        xButton2 = new com.rameses.rcp.control.XButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        xPanel2.setLayout(new java.awt.BorderLayout());

        xPanel1.setVisibleWhen("#{mode == 'processing'}");
        xPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        xPanel1.setLayout(new java.awt.BorderLayout());

        xLabel1.setFontStyle("font-weight:bold;font-size:12;");
        xLabel1.setForeground(new java.awt.Color(51, 51, 51));
        xLabel1.setPadding(new java.awt.Insets(1, 5, 1, 1));
        xLabel1.setPreferredSize(new java.awt.Dimension(150, 20));
        xLabel1.setText("Processing request please wait...");
        xPanel1.add(xLabel1, java.awt.BorderLayout.CENTER);

        xLabel2.setIconResource("com/rameses/rcp/icons/loading16.gif");
        xPanel1.add(xLabel2, java.awt.BorderLayout.WEST);

        xPanel2.add(xPanel1, java.awt.BorderLayout.NORTH);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("  General Information   ");
        jPanel1.setBorder(xTitledBorder1);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        xFormPanel1.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xFormPanel1.setCaptionWidth(110);
        xFormPanel1.setCellspacing(3);
        xFormPanel1.setPadding(new java.awt.Insets(10, 10, 10, 10));

        xComboBox8.setCaption("Template");
        xComboBox8.setExpression("  #{item.name}");
        xComboBox8.setItems("templateTypes");
        xComboBox8.setName("entity.template"); // NOI18N
        xComboBox8.setAllowNull(false);
        xComboBox8.setCaptionWidth(120);
        xComboBox8.setImmediate(true);
        xComboBox8.setPreferredSize(new java.awt.Dimension(300, 22));
        xComboBox8.setRequired(true);
        xFormPanel1.add(xComboBox8);

        xComboBox7.setCaption("Posting Type");
        xComboBox7.setExpression("  #{item.name}");
        xComboBox7.setItems("postingTypes");
        xComboBox7.setName("entity.postingtype"); // NOI18N
        xComboBox7.setAllowNull(false);
        xComboBox7.setCaptionWidth(120);
        xComboBox7.setImmediate(true);
        xComboBox7.setPreferredSize(new java.awt.Dimension(300, 22));
        xComboBox7.setRequired(true);
        xFormPanel1.add(xComboBox7);

        xComboBox1.setCaption("Period");
        xComboBox1.setExpression("  #{item.title}");
        xComboBox1.setItemKey("type");
        xComboBox1.setItems("periodUtil.types");
        xComboBox1.setName("entity.period"); // NOI18N
        xComboBox1.setAllowNull(false);
        xComboBox1.setCaptionWidth(120);
        xComboBox1.setImmediate(true);
        xComboBox1.setPreferredSize(new java.awt.Dimension(100, 22));
        xComboBox1.setRequired(true);
        xFormPanel1.add(xComboBox1);

        xIntegerField1.setCaption("Year");
        xIntegerField1.setDepends(new String[] {"entity.period"});
        xIntegerField1.setName("entity.year"); // NOI18N
        xIntegerField1.setCaptionWidth(120);
        xIntegerField1.setPreferredSize(new java.awt.Dimension(100, 22));
        xIntegerField1.setRequired(true);
        xFormPanel1.add(xIntegerField1);

        xComboBox2.setCaption("Quarter");
        xComboBox2.setDepends(new String[] {"entity.period"});
        xComboBox2.setExpression("  #{item}");
        xComboBox2.setItems("quarters");
        xComboBox2.setName("entity.qtr"); // NOI18N
        xComboBox2.setCaptionWidth(120);
        xComboBox2.setImmediate(true);
        xComboBox2.setPreferredSize(new java.awt.Dimension(100, 22));
        xComboBox2.setRequired(true);
        xFormPanel1.add(xComboBox2);

        xComboBox3.setCaption("Month");
        xComboBox3.setDepends(new String[] {"entity.period"});
        xComboBox3.setExpression("  #{item.title}");
        xComboBox3.setItems("periodUtil.months");
        xComboBox3.setName("entity.month"); // NOI18N
        xComboBox3.setCaptionWidth(120);
        xComboBox3.setImmediate(true);
        xComboBox3.setPreferredSize(new java.awt.Dimension(100, 22));
        xComboBox3.setRequired(true);
        xFormPanel1.add(xComboBox3);

        xDateField1.setCaption("Date");
        xDateField1.setDepends(new String[] {"entity.period"});
        xDateField1.setName("entity.date"); // NOI18N
        xDateField1.setCaptionWidth(120);
        xDateField1.setPreferredSize(new java.awt.Dimension(100, 22));
        xDateField1.setRequired(true);
        xFormPanel1.add(xDateField1);

        xDateField2.setCaption("Start Date");
        xDateField2.setDepends(new String[] {"entity.period"});
        xDateField2.setName("entity.startdate"); // NOI18N
        xDateField2.setCaptionWidth(120);
        xDateField2.setPreferredSize(new java.awt.Dimension(100, 22));
        xDateField2.setRequired(true);
        xFormPanel1.add(xDateField2);

        xDateField3.setCaption("End  Date");
        xDateField3.setDepends(new String[] {"entity.period"});
        xDateField3.setName("entity.enddate"); // NOI18N
        xDateField3.setCaptionWidth(120);
        xDateField3.setPreferredSize(new java.awt.Dimension(100, 22));
        xDateField3.setRequired(true);
        xFormPanel1.add(xDateField3);

        jPanel1.add(xFormPanel1);

        xPanel2.add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.add(xPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        xLabel3.setExpression("Item Accounts");
        xLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 5, 0));
        xLabel3.setFontStyle("font-weight: bold;");
        xLabel3.setPreferredSize(new java.awt.Dimension(600, 31));
        jPanel3.add(xLabel3, java.awt.BorderLayout.NORTH);

        xDataTable1.setHandler("itemAcctListHandler");
        xDataTable1.setName("selectedItem"); // NOI18N
        xDataTable1.setColumns(new com.rameses.rcp.common.Column[]{
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "code"}
                , new Object[]{"caption", "Code"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 200}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "title"}
                , new Object[]{"caption", "Title"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "fund.title"}
                , new Object[]{"caption", "Fund"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            })
        });
        jPanel3.add(xDataTable1, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 0, 0));
        com.rameses.rcp.control.layout.XLayout xLayout1 = new com.rameses.rcp.control.layout.XLayout();
        xLayout1.setSpacing(5);
        jPanel4.setLayout(xLayout1);

        xButton1.setName("addItem"); // NOI18N
        xButton1.setImmediate(true);
        xButton1.setText("  Add  ");
        jPanel4.add(xButton1);

        xButton2.setDepends(new String[] {"selectedItem"});
        xButton2.setDisableWhen("#{hasSelectedItems == false}");
        xButton2.setName("removeItem"); // NOI18N
        xButton2.setImmediate(true);
        xButton2.setText("Remove");
        jPanel4.add(xButton2);

        jPanel3.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XComboBox xComboBox7;
    private com.rameses.rcp.control.XComboBox xComboBox8;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XDateField xDateField3;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XPanel xPanel2;
    // End of variables declaration//GEN-END:variables
}
