/*
 * PreviewByFundPage.java
 *
 * Created on August 19, 2013, 11:47 PM
 */

package com.rameses.gov.treasury.report.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  arnelretiza
 */
@Template(FormPage.class)
public class PreviewByFundPage extends javax.swing.JPanel {
    
    /** Creates new form PreviewByFundPage */
    public PreviewByFundPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        jPanel3 = new javax.swing.JPanel();
        xReportPanel1 = new com.rameses.osiris2.reports.ui.XReportPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 3, 0));
        com.rameses.rcp.control.layout.XLayout xLayout1 = new com.rameses.rcp.control.layout.XLayout();
        xLayout1.setSpacing(10);
        jPanel2.setLayout(xLayout1);

        xLabel1.setText("Fund :");
        jPanel2.add(xLabel1);

        xComboBox1.setCaption("Fund");
        xComboBox1.setExpression("#{item.title}");
        xComboBox1.setItems("funds");
        xComboBox1.setName("fund"); // NOI18N
        xComboBox1.setCaptionWidth(70);
        xComboBox1.setDynamic(true);
        jPanel2.add(xComboBox1);

        jPanel3.setName("filter"); // NOI18N
        jPanel3.setLayout(new com.rameses.rcp.control.layout.XLayout());
        jPanel2.add(jPanel3);

        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        xReportPanel1.setDepends(new String[] {"fund"});
        xReportPanel1.setName("report"); // NOI18N

        org.jdesktop.layout.GroupLayout xReportPanel1Layout = new org.jdesktop.layout.GroupLayout(xReportPanel1);
        xReportPanel1.setLayout(xReportPanel1Layout);
        xReportPanel1Layout.setHorizontalGroup(
            xReportPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 604, Short.MAX_VALUE)
        );
        xReportPanel1Layout.setVerticalGroup(
            xReportPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 339, Short.MAX_VALUE)
        );

        add(xReportPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.osiris2.reports.ui.XReportPanel xReportPanel1;
    // End of variables declaration//GEN-END:variables
    
}
