/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.treasury.tool.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author ramesesinc
 */
@Template(FormPage.class)
public class ConvertAFIssuanceInitPage extends javax.swing.JPanel {

    /**
     * Creates new form ConvertAFIssuanceInitPage
     */
    public ConvertAFIssuanceInitPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xLabel4 = new com.rameses.rcp.control.XLabel();

        xFormPanel1.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xFormPanel1.setCaptionWidth(120);
        xFormPanel1.setCellspacing(4);
        xFormPanel1.setPadding(new java.awt.Insets(0, 5, 5, 0));

        xLookupField1.setCaption("AF Issuance No.");
        xLookupField1.setExpression("#{afissue.controlno}");
        xLookupField1.setHandler("lookupAFIssue");
        xLookupField1.setName("afissue"); // NOI18N
        xLookupField1.setRequired(true);
        xLookupField1.setStretchWidth(100);
        xFormPanel1.add(xLookupField1);

        xLabel1.setCaption("Control Date");
        xLabel1.setDepends(new String[] {"afissue"});
        xLabel1.setExpression("#{afissue.dtfiled}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder1 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder1.setLineColor(new java.awt.Color(180, 180, 180));
        xLineBorder1.setPadding(new java.awt.Insets(1, 0, 1, 0));
        xLabel1.setBorder(xLineBorder1);
        xLabel1.setDateFormat("yyyy-MM-dd");
        xLabel1.setStretchWidth(100);
        xFormPanel1.add(xLabel1);

        xLabel2.setCaption("Created By");
        xLabel2.setDepends(new String[] {"afissue"});
        xLabel2.setExpression("#{afissue.user.name}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder2 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder2.setLineColor(new java.awt.Color(180, 180, 180));
        xLineBorder2.setPadding(new java.awt.Insets(1, 0, 1, 0));
        xLabel2.setBorder(xLineBorder2);
        xLabel2.setDateFormat("yyyy-MM-dd");
        xLabel2.setStretchWidth(100);
        xFormPanel1.add(xLabel2);

        xLabel3.setCaption("Issued To");
        xLabel3.setDepends(new String[] {"afissue"});
        xLabel3.setExpression("#{afissue.issueto.name}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder3 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder3.setLineColor(new java.awt.Color(180, 180, 180));
        xLineBorder3.setPadding(new java.awt.Insets(1, 0, 1, 0));
        xLabel3.setBorder(xLineBorder3);
        xLabel3.setDateFormat("yyyy-MM-dd");
        xLabel3.setStretchWidth(100);
        xFormPanel1.add(xLabel3);

        xLabel4.setCaption("Request No.");
        xLabel4.setDepends(new String[] {"afissue"});
        xLabel4.setExpression("#{afissue.request.reqno}");
        com.rameses.rcp.control.border.XLineBorder xLineBorder4 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder4.setLineColor(new java.awt.Color(180, 180, 180));
        xLineBorder4.setPadding(new java.awt.Insets(1, 0, 1, 0));
        xLabel4.setBorder(xLineBorder4);
        xLabel4.setDateFormat("yyyy-MM-dd");
        xLabel4.setStretchWidth(100);
        xFormPanel1.add(xLabel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    // End of variables declaration//GEN-END:variables
}
