/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.treasury.tool.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author ramesesinc
 */
@StyleSheet
@Template(FormPage.class)
public class IncomeSummaryInitPage extends javax.swing.JPanel {

    /**
     * Creates new form IncomeSummaryInitPage
     */
    public IncomeSummaryInitPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xIntegerField2 = new com.rameses.rcp.control.XIntegerField();
        xComboBox4 = new com.rameses.rcp.control.XComboBox();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xIntegerField3 = new com.rameses.rcp.control.XIntegerField();
        xComboBox5 = new com.rameses.rcp.control.XComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        xHtmlView1 = new com.rameses.rcp.control.XHtmlView();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setPadding(new java.awt.Insets(30, 15, 15, 15));
        xTitledBorder1.setTitle("  General Informatoin    ");
        xFormPanel1.setBorder(xTitledBorder1);
        xFormPanel1.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xFormPanel1.setCaptionWidth(100);
        xFormPanel1.setCellspacing(4);

        xComboBox1.setCaption("Posting Type");
        xComboBox1.setExpression("#{item.name}");
        xComboBox1.setItems("postingTypes");
        xComboBox1.setName("entity.postingtype"); // NOI18N
        xComboBox1.setRequired(true);
        xComboBox1.setStretchWidth(100);
        xFormPanel1.add(xComboBox1);

        xFormPanel2.setCaption("Start Date");
        xFormPanel2.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xFormPanel2.setCaptionWidth(100);
        xFormPanel2.setCellspacing(4);
        xFormPanel2.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel2.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel2.setStretchWidth(100);

        xIntegerField2.setCaption("Start Year");
        xIntegerField2.setName("entity.startyear"); // NOI18N
        xIntegerField2.setRequired(true);
        xIntegerField2.setShowCaption(false);
        xFormPanel2.add(xIntegerField2);

        xComboBox4.setCaption("Start Month");
        xComboBox4.setExpression("#{item.name}");
        xComboBox4.setItems("months");
        xComboBox4.setName("entity.startmonth"); // NOI18N
        xComboBox4.setRequired(true);
        xComboBox4.setShowCaption(false);
        xComboBox4.setStretchWidth(100);
        xFormPanel2.add(xComboBox4);

        xFormPanel1.add(xFormPanel2);

        xFormPanel3.setCaption("End Date");
        xFormPanel3.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xFormPanel3.setCaptionWidth(100);
        xFormPanel3.setCellspacing(4);
        xFormPanel3.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel3.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel3.setStretchWidth(100);

        xIntegerField3.setCaption("End Year");
        xIntegerField3.setName("entity.endyear"); // NOI18N
        xIntegerField3.setRequired(true);
        xIntegerField3.setShowCaption(false);
        xFormPanel3.add(xIntegerField3);

        xComboBox5.setCaption("End Month");
        xComboBox5.setExpression("#{item.name}");
        xComboBox5.setItems("months");
        xComboBox5.setName("entity.endmonth"); // NOI18N
        xComboBox5.setRequired(true);
        xComboBox5.setShowCaption(false);
        xComboBox5.setStretchWidth(100);
        xFormPanel3.add(xComboBox5);

        xFormPanel1.add(xFormPanel3);

        xHtmlView1.setName("infoHandler"); // NOI18N
        xHtmlView1.setDynamic(true);
        jScrollPane1.setViewportView(xHtmlView1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox4;
    private com.rameses.rcp.control.XComboBox xComboBox5;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XHtmlView xHtmlView1;
    private com.rameses.rcp.control.XIntegerField xIntegerField2;
    private com.rameses.rcp.control.XIntegerField xIntegerField3;
    // End of variables declaration//GEN-END:variables
}
