/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.treasury.tool.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author ramesesinc
 */
@Template(FormPage.class)
public class RebuildProcErrorPage extends javax.swing.JPanel {

    /**
     * Creates new form RebuildProcErrorPage
     */
    public RebuildProcErrorPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xLabel2 = new com.rameses.rcp.control.XLabel();
        xLabel3 = new com.rameses.rcp.control.XLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 20, 20));
        setPreferredSize(new java.awt.Dimension(503, 162));
        setLayout(new java.awt.BorderLayout());

        xLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        xLabel2.setForeground(new java.awt.Color(255, 0, 0));
        xLabel2.setIconResource("images/error-icon.png");
        add(xLabel2, java.awt.BorderLayout.WEST);

        xLabel3.setExpression("#{errormessage}");
        xLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel3.setFontStyle("font-size:12; ");
        xLabel3.setUseHtml(true);
        add(xLabel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    // End of variables declaration//GEN-END:variables
}
