/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.enterprise.treasury.views;

/**
 *
 * @author Elmo Nazareno
 */
public class CashReceiptPostConfirmPage extends javax.swing.JPanel {

    /**
     * Creates new form CashReceiptPostConfirmPage
     */
    public CashReceiptPostConfirmPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        xButton1 = new com.rameses.rcp.control.XButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        xButton2 = new com.rameses.rcp.control.XButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setMinimumSize(new java.awt.Dimension(645, 317));
        setPreferredSize(new java.awt.Dimension(645, 317));
        setLayout(new java.awt.BorderLayout());

        xLabel1.setExpression("<html> Please ensure that the following receipt number matches the actual receipt to use.<br/> <u>Do not proceed if it does not match</u>. Press Enter or click OK to confirm</html>");
        xLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        xLabel1.setFontStyle("font-size: 14; font-weight: bold;");
        xLabel1.setForeground(new java.awt.Color(204, 0, 0));
        add(xLabel1, java.awt.BorderLayout.NORTH);

        xLabel2.setExpression("#{receiptno}");
        xLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 20, 20));
        xLabel2.setFontStyle("font-size:36; font-weight: bold;");
        xLabel2.setUseHtml(true);
        add(xLabel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(filler1);

        xButton1.setMnemonic('k');
        xButton1.setName("doOk"); // NOI18N
        xButton1.setDefaultCommand(true);
        xButton1.setFocusable(false);
        xButton1.setFontStyle("font-size: 14;");
        xButton1.setMargin(new java.awt.Insets(6, 20, 6, 20));
        xButton1.setText("  OK  ");
        xButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(xButton1);
        jPanel1.add(filler3);

        xButton2.setMnemonic('c');
        xButton2.setName("doCancel"); // NOI18N
        xButton2.setAccelerator("27");
        xButton2.setFocusable(false);
        xButton2.setFontStyle("font-size: 14;");
        xButton2.setMargin(new java.awt.Insets(6, 20, 6, 20));
        xButton2.setText("Cancel");
        jPanel1.add(xButton2);
        jPanel1.add(filler2);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void xButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JPanel jPanel1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    // End of variables declaration//GEN-END:variables
}
