/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.enterprise.treasury.views;

/**
 *
 * @author ramesesinc
 */
public class CreditMemoQueryFormPage extends javax.swing.JPanel {

    /**
     * Creates new form CreditMemoQueryFormPage
     */
    public CreditMemoQueryFormPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xLabel2 = new com.rameses.rcp.control.XLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new com.rameses.rcp.control.layout.XLayout());

        xLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        xLabel1.setText("Sort By");
        jPanel1.add(xLabel1);

        xComboBox1.setExpression("#{item.title}");
        xComboBox1.setItems("sortfields");
        xComboBox1.setName("sortfield"); // NOI18N
        jPanel1.add(xComboBox1);

        xComboBox2.setItems("sorttypes");
        xComboBox2.setName("sorttype"); // NOI18N
        xComboBox2.setAllowNull(false);
        jPanel1.add(xComboBox2);

        xLabel2.setExpression("Search");
        xLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        jPanel1.add(xLabel2);

        add(jPanel1, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    // End of variables declaration//GEN-END:variables
}
